#应用组织信息（可选）
app: loan-service # 应用名称。留空则默认取当前组件的实例名称为app名称。
stage: ${env.STAGE}  # 环境名称。默认值是 dev。建议使用 ${env.STAGE} 变量定义环境名称

#组件信息
component: scf # (必选) 组件名称，在该实例中为 scf
name: loan-handler # (必选) 组件实例名称。

#组件参数配置，根据每个组件，实现具体的资源信息配置
inputs:
  name: loan-${stage} # 云函数名称，默认为 ${name}-${stage}-${app}
  src: ./src # 项目代码路径，默认写法，新建特定命名的 COS Bucket 并上传
  handler: index.main_handler #入口
  runtime: Nodejs10.15 # 运行环境 默认 Nodejs10.15
  region: ap-shanghai # 函数所在区域
  description: This is a function in ${app} application.
  environment: #  环境变量
    variables: #  环境变量对象
      TEST: value
  layers: #layer配置
    - name: scfLayer #  layer名称
      version: 1 #  版本
  events: # 触发器配置
    - timer: # 定时触发器
        parameters:
          cronExpression: '*/5 * * * * * *' # 每5秒触发一次
          enable: true